// DATA TYPES
export const ADD_POST ='ADD_POST'
export const EDIT_POST ='EDIT_POST'
export const FETCH_POST ='FETCH_POST'
export const FETCH_POSTS ='FETCH_POSTS'
export const FETCH_IMGUR_POSTS ='FETCH_IMGUR_POSTS'
export const FETCH_POSTS_ERROR ='FETCH_POSTS_ERROR'
export const INCREMENT_LIKE_COUNTER = 'INCREMENT_LIKE_COUNTER'
export const DECREMENT_LIKE_COUNTER = 'DECREMENT_LIKE_COUNTER'

// LOGIN TYPES
export const LOGIN_USER_FORM = 'LOGIN_USER_FORM'
export const LOGOUT_USER_FORM = 'LOGOUT_USER_FORM'
export const LOGIN_USER_GITHUB = 'LOGIN_USER_GITHUB'
export const LOGOUT_USER_GITHUB = 'LOGOUT_USER_GITHUB'
